--------------------------------------------
-- VER TODAS LAS TABLAS.
--------------------------------------------
SELECT * FROM SALESPEOPLE; 
SELECT * FROM CUSTOMERS; 
SELECT * FROM CARS; 
SELECT * FROM SALES_INVOICES; 
SELECT * FROM MECHANICS; 
SELECT * FROM SERVICES; 
SELECT * FROM SERVICE_TICKETS; 
SELECT * FROM SERVICE_MECHANICS; 
SELECT * FROM PARTS; 
SELECT * FROM PARTS_USED;  