--------------------------------------------
-- LIMPIAR LA BASE DE DATOS.
--------------------------------------------
DELETE FROM PARTS_USED;
DELETE FROM SERVICE_MECHANICS;
DELETE FROM SERVICE_TICKETS;
DELETE FROM PARTS;
DELETE FROM SERVICES;
DELETE FROM MECHANICS;
DELETE FROM SALES_INVOICES;
DELETE FROM CARS;
DELETE FROM CUSTOMERS;
DELETE FROM SALESPEOPLE;